import { SalesContract, SOWithoutContract } from '../types/salescontract.types';
import { mockSalesContracts, mockSOWithoutContracts } from '../data/mockSalesContracts';

// Mocking API delays
const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

let salesContracts = [...mockSalesContracts];
let soWithoutContracts = [...mockSOWithoutContracts];

export const salescontractApi = {
    fetchSalesContracts: async (): Promise<SalesContract[]> => {
        await delay(500);
        return [...salesContracts];
    },

    getSalesContractById: async (id: string): Promise<SalesContract | undefined> => {
        await delay(500);
        return salesContracts.find(sc => sc.id_sales_contract === id);
    },

    fetchSOWithoutContract: async (): Promise<SOWithoutContract[]> => {
        await delay(500);
        return [...soWithoutContracts];
    },
    
    getSOWithoutContractById: async (id: string): Promise<SOWithoutContract | undefined> => {
        await delay(500);
        return soWithoutContracts.find(so => so.id_so === id);
    },

    createSalesContract: async (data: SalesContract): Promise<SalesContract> => {
        await delay(800);
        const newSC = { ...data };
        // In real API, id is generated by backend. We mock it here.
        if (!newSC.id_sales_contract) {
            newSC.id_sales_contract = `SC-${Date.now()}`;
        }
        if (!newSC.code_sales_contract) {
            newSC.code_sales_contract = `SC/NEW/${Date.now()}`;
        }
        
        salesContracts = [newSC, ...salesContracts];
        
        // Remove from SOWithoutContract
        soWithoutContracts = soWithoutContracts.filter(so => so.id_so !== newSC.id_so);
        
        return newSC;
    },

    updateSalesContract: async (id: string, data: Partial<SalesContract>): Promise<SalesContract> => {
        await delay(800);
        const index = salesContracts.findIndex(sc => sc.id_sales_contract === id);
        if (index === -1) {
            throw new Error("Sales Contract not found");
        }
        
        salesContracts[index] = { ...salesContracts[index], ...data };
        return salesContracts[index];
    }
};
